name:                comp-programming
version:             0.1.0.0
github:              "githubuser/comp-programming"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/comp-programming#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  comp-programming-exe:
    #main:                app/ABC197/E.hs
    #main:                app/Main.hs
    #main: app/Test.hs
    main: app/GreenProblems/ARC067C.hs
    # source-dirs:         
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - array
    - primitive
    - vector-algorithms
    - repa
    - vector
    - bytestring
    - comp-programming

tests:
  comp-programming-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - comp-programming
